import {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
} from '@expo/config-plugins';
import type { ConfigPlugin } from '@expo/config-plugins';
import { promises as fs } from 'fs';
import * as path from 'path';

/**
 * Expo config plugin for react-native-cache-video.
 *
 * The library runs a localhost HTTP proxy (NanoHTTPD on Android, an Obj-C++ proxy on
 * iOS) and reverse-proxies video through `http://127.0.0.1:<port>`. Cleartext traffic to
 * loopback is intrinsic to how the proxy serves cached bytes, so a prebuilt app needs:
 *   - Android: cleartext permitted to 127.0.0.1 / localhost (scoped, not blanket)
 *   - iOS:     an ATS exception for localhost / 127.0.0.1 (localhost is NOT ATS-exempt here —
 *              proven by the bundled example/ios Info.plist)
 *
 * The plugin injects exactly that and nothing else. The TurboModule itself autolinks through
 * React Native autolinking (which Expo prebuild respects), so no autolinking glue is added.
 */

const NSC_RESOURCE = 'rncachevideo_network_security_config';
const NSC_ATTRIBUTE = 'android:networkSecurityConfig';
const LOOPBACK_DOMAINS = ['127.0.0.1', 'localhost'];

const NSC_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by react-native-cache-video config plugin. Scopes cleartext to loopback only. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
`;

/** Android: write a scoped network-security-config and point the manifest at it. */
const withAndroidCleartextLoopback: ConfigPlugin = (config) => {
  // 1. Write res/xml/<resource>.xml (idempotent — same content every run).
  const withResource = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const resXmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml'
      );
      await fs.mkdir(resXmlDir, { recursive: true });
      await fs.writeFile(path.join(resXmlDir, `${NSC_RESOURCE}.xml`), NSC_XML);
      return cfg;
    },
  ]);

  // 2. Point <application> at our network-security-config. Don't clobber a config the host
  //    app (or another plugin) already declares — two arbitrary NSC resources can't be safely
  //    merged at prebuild, so we preserve theirs and warn. Idempotent for our own value.
  return withAndroidManifest(withResource, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults
    );
    const ours = `@xml/${NSC_RESOURCE}`;
    const existing = application.$[NSC_ATTRIBUTE];
    if (existing && existing !== ours) {
      console.warn(
        `[react-native-cache-video] app already sets android:networkSecurityConfig="${existing}"; ` +
          `leaving it untouched. Add a cleartext domain-config for 127.0.0.1 and localhost to that file.`
      );
      return cfg;
    }
    application.$[NSC_ATTRIBUTE] = ours;
    return cfg;
  });
};

/** iOS: merge an ATS localhost/127.0.0.1 exception, preserving any existing ATS config. */
const withIosAtsLoopback: ConfigPlugin = (config) =>
  withInfoPlist(config, (cfg) => {
    // Treat the plist loosely for this merge — the InfoPlist JSONValue typing does not model
    // nested ATS dictionaries, and we must preserve any keys the app already declares.
    const infoPlist = cfg.modResults as Record<string, any>;
    const existing = infoPlist.NSAppTransportSecurity ?? {};
    const domains: Record<string, any> = {
      ...(existing.NSExceptionDomains ?? {}),
    };
    for (const domain of LOOPBACK_DOMAINS) {
      domains[domain] = {
        ...domains[domain],
        NSExceptionAllowsInsecureHTTPLoads: true,
      };
    }
    // Deliberately NOT setting NSAllowsArbitraryLoads — that is the RN dev-server's concern,
    // not ours, and would be an over-broad (App-Store-flagged) exception.
    infoPlist.NSAppTransportSecurity = {
      ...existing,
      NSExceptionDomains: domains,
    };
    return cfg;
  });

const withRnCacheVideo: ConfigPlugin = (config) => {
  const withAndroid = withAndroidCleartextLoopback(config);
  return withIosAtsLoopback(withAndroid);
};

export default withRnCacheVideo;
